config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#index"
  get '/users/:id' => "users#show", as: 'user'

  get '/login' => 'sessions#new'
  post '/login' =>'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user, inverse_of: :sessions
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true

  has_many :sessions, dependent: :destroy, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_session
    unless defined? @current_session
      @current_session = Session.find_by(token: cookies['_session_id'])
    end

    @current_session
  end
  helper_method :current_session

  def current_user
    current_session&.user
  end
  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include PagesHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])&.authenticate(params[:password])

    if user
      # Successfull flow
      session = user.sessions.create!(token: SecureRandom.uuid)

      cookies['_session_id'] = {
        value: session.token,
        path: '/',
        secure: false,
        httponly: true,
      }

      redirect_to root_path, notice: "Hello, #{params[:email]}"
    else
      flash[:error] = "Incorrect email or password"
      render :new
    end
  end

  def destroy
    @user = current_user
    current_session&.destroy
    cookies['_session_id'] = {
      value: '',
      #expires: -1,
      max_age: -1,
      path: '/',
      secure: false,
      httponly: true,
    }
    redirect_to root_path, notice: "Goodbye, #{@user.name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def full_name
    'Vasya Pupkin'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_navigation.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">My App</a>
      <% if current_user %>
        <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Login", login_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>

    <div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:error].present? %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
  <p>Hello, <%= current_user.name %></p>

  <%= link_to user_path(current_user.id) do %>
    User: <%= current_user.name %>
  <% end %>

  <br/>
  <%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
  <p> Please <%= link_to 'login', login_path %> </p>
<% end %>